# Generated by Django 3.0.7 on 2020-07-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AVShop', '0003_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(height_field=100, upload_to='media', width_field=100),
        ),
    ]
